services:
  portfolio:
    image: ${PORTFOLIO_IMAGE}:${PORTFOLIO_TAG}
    ports:
      - "${PORTFOLIO_HOST_PORT}:${PORTFOLIO_INTERNAL_PORT}"
    depends_on:
      - admin-system1

  admin-system1:
    image: ${ADMIN_SYSTEM1_IMAGE}:${ADMIN_SYSTEM1_TAG}
    ports:
      - "${ADMIN_SYSTEM1_HOST_PORT}:${ADMIN_SYSTEM1_INTERNAL_PORT}"